import React, { useState } from 'react';
import styled, { css } from 'styled-components';
import VisibilitySensor from 'react-visibility-sensor';

export interface ImageAnimationProps {
  image: string;
  imageAlt: string;
  imageStyle?: React.CSSProperties | undefined;
  animationDirection:
    | 'TopRightToLeft'
    | 'TopLeftToRight'
    | 'RightToLeft'
    | 'BottomToTop'
    | 'FadeIn';
  animationX?: string;
  animationRotation?: string;
  animationDuration?: number;
  showOnPhone?: boolean;
  boxShadow?: boolean;
}

export const ImageAnimation: React.FC<ImageAnimationProps> = ({
  image,
  imageAlt,
  imageStyle,
  animationDirection,
  animationX,
  animationRotation,
  animationDuration,
  showOnPhone,
  boxShadow,
}) => {
  const [isVisible, setIsVisible] = useState<boolean>(false);

  return (
    <VisibilitySensor
      partialVisibility
      active={!isVisible}
      onChange={(isVisibleNewValue: boolean) => {
        setIsVisible(isVisibleNewValue);
      }}
    >
      <Image
        src={image}
        alt={imageAlt}
        isVisible={isVisible}
        animationDirection={animationDirection}
        animationX={animationX}
        animationRotation={animationRotation}
        animationDuration={animationDuration}
        showOnPhone={showOnPhone}
        style={imageStyle}
        boxShadow={boxShadow}
      />
    </VisibilitySensor>
  );
};

const Image = styled.img<{
  isVisible: boolean;
  animationDirection:
    | 'TopRightToLeft'
    | 'TopLeftToRight'
    | 'RightToLeft'
    | 'BottomToTop'
    | 'FadeIn';
  animationX?: string;
  animationRotation?: string;
  animationDuration?: number;
  showOnPhone?: boolean;
  boxShadow?: boolean;
}>`
  --animationX: ${(props) => (props.animationX ? props.animationX : '100px')};
  --negativeAnimationX: calc(-1 * var(--animationX));
  --animationRotation: ${(props) =>
    props.animationRotation ? props.animationRotation : '5deg'};
  --animationDuration: ${(props) =>
    props.animationDuration ? props.animationDuration + 's' : '0.7s'};

  /* ----------------------------------------------
 * Generated by Animista on 2020-12-6 20:56:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation slide-bl
 * ----------------------------------------
 */
  @-webkit-keyframes slide-bl {
    0% {
      opacity: 0;
      -webkit-transform: translateY(0) translateX(0) rotate(0deg);
      transform: translateY(0) translateX(0) rotate(0deg);
    }
    25% {
      opacity: 0;
    }
    100% {
      opacity: 1;
      -webkit-transform: translateY(var(--animationX))
        translateX(var(--negativeAnimationX)) rotate(var(--animationRotation));
      transform: translateY(var(--animationX))
        translateX(var(--negativeAnimationX)) rotate(var(--animationRotation));
    }
  }
  @keyframes slide-bl {
    0% {
      opacity: 0;
      -webkit-transform: translateY(0) translateX(0) rotate(0deg);
      transform: translateY(0) translateX(0) rotate(0deg);
    }
    25% {
      opacity: 0;
    }
    100% {
      opacity: 1;
      -webkit-transform: translateY(var(--animationX))
        translateX(var(--negativeAnimationX)) rotate(var(--animationRotation));
      transform: translateY(var(--animationX))
        translateX(var(--negativeAnimationX)) rotate(var(--animationRotation));
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2020-12-7 15:22:17
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation slide-br
 * ----------------------------------------
 */
  @-webkit-keyframes slide-br {
    0% {
      opacity: 0;
      -webkit-transform: translateY(0) translateX(0) rotate(0deg);
      transform: translateY(0) translateX(0) rotate(0deg);
    }
    25% {
      opacity: 0;
    }
    100% {
      opacity: 1;
      -webkit-transform: translateY(var(--animationX))
        translateX(var(--animationX)) rotate(var(--animationRotation));
      transform: translateY(var(--animationX)) translateX(var(--animationX))
        rotate(var(--animationRotation));
    }
  }
  @keyframes slide-br {
    0% {
      opacity: 0;
      -webkit-transform: translateY(0) translateX(0) rotate(0deg);
      transform: translateY(0) translateX(0) rotate(0deg);
    }
    25% {
      opacity: 0;
    }
    100% {
      opacity: 1;
      -webkit-transform: translateY(var(--animationX))
        translateX(var(--animationX)) rotate(var(--animationRotation));
      transform: translateY(var(--animationX)) translateX(var(--animationX))
        rotate(var(--animationRotation));
    }
  }

  /**
 * ----------------------------------------
 * animation slide-l2r
 * ----------------------------------------
 */
  @-webkit-keyframes slide-l2r {
    0% {
      opacity: 0;
      -webkit-transform: translateX(0) rotate(0deg);
      transform: translateX(0) rotate(0deg);
    }
    25% {
      opacity: 0;
    }
    100% {
      opacity: 1;
      -webkit-transform: translateX(var(--negativeAnimationX))
        rotate(var(--animationRotation));
      transform: translateX(var(--negativeAnimationX))
        rotate(var(--animationRotation));
    }
  }
  @keyframes slide-l2r {
    0% {
      opacity: 0;
      -webkit-transform: translateX(0) rotate(0deg);
      transform: translateX(0) rotate(0deg);
    }
    25% {
      opacity: 0;
    }
    100% {
      opacity: 1;
      -webkit-transform: translateX(var(--negativeAnimationX))
        rotate(var(--animationRotation));
      transform: translateX(var(--negativeAnimationX))
        rotate(var(--animationRotation));
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2020-12-8 20:37:20
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
  @-webkit-keyframes slide-top {
    0% {
      opacity: 0;
      -webkit-transform: translateY(0);
      transform: translateY(0);
    }
    25% {
      opacity: 0;
    }
    100% {
      opacity: 1;
      -webkit-transform: translateY(var(--negativeAnimationX));
      transform: translateY(var(--negativeAnimationX));
    }
  }
  @keyframes slide-top {
    0% {
      opacity: 0;
      -webkit-transform: translateY(0);
      transform: translateY(0);
    }
    25% {
      opacity: 0;
    }
    100% {
      opacity: 1;
      -webkit-transform: translateY(var(--negativeAnimationX));
      transform: translateY(var(--negativeAnimationX));
    }
  }

  /**
   * ----------------------------------------
   * animation fade-in
   * ----------------------------------------
   */
  @-webkit-keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
  @keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }

  ${(props) =>
    props.showOnPhone
      ? css`
          display: initial;
        `
      : css`
          display: none;
        `}
  opacity: 0;

  @media (min-width: 768px) {
    display: initial;
  }

  ${(props) =>
    props.isVisible &&
    props.animationDirection === 'TopRightToLeft' &&
    css`
      -webkit-animation: slide-bl var(--animationDuration)
        cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
      animation: slide-bl var(--animationDuration)
        cubic-bezier(0.25, 0.46, 0.45, 0.94) both;

      ${props.boxShadow &&
      css`
        box-shadow: 5px -5px rgb(33, 41, 48, 0.4),
          10px -10px rgb(33, 41, 48, 0.3), 15px -15px rgb(33, 41, 48, 0.2),
          20px -20px rgb(33, 41, 48, 0.1), 25px -25px rgb(33, 41, 48, 0.05);
      `}
    `}

  ${(props) =>
    props.isVisible &&
    props.animationDirection === 'TopLeftToRight' &&
    css`
      -webkit-animation: slide-br var(--animationDuration)
        cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
      animation: slide-br var(--animationDuration)
        cubic-bezier(0.25, 0.46, 0.45, 0.94) both;

      ${props.boxShadow &&
      css`
        box-shadow: -5px -5px rgb(33, 41, 48, 0.4),
          -10px -10px rgb(33, 41, 48, 0.3), -15px -15px rgb(33, 41, 48, 0.2),
          -20px -20px rgb(33, 41, 48, 0.1), -25px -25px rgb(33, 41, 48, 0.05);
      `}
    `}

    ${(props) =>
    props.isVisible &&
    props.animationDirection === 'RightToLeft' &&
    css`
      -webkit-animation: slide-l2r var(--animationDuration)
        cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
      animation: slide-l2r var(--animationDuration)
        cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    `}

    ${(props) =>
    props.isVisible &&
    props.animationDirection === 'BottomToTop' &&
    css`
      -webkit-animation: slide-top var(--animationDuration)
        cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
      animation: slide-top var(--animationDuration)
        cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    `}

    ${(props) =>
    props.isVisible &&
    props.animationDirection === 'FadeIn' &&
    css`
      -webkit-animation: fade-in var(--animationDuration)
        cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
      animation: fade-in var(--animationDuration)
        cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    `}
`;
